const {
  CRYPTOCOMPARE_RETRY_DELAY = 100,
  CRYPTOCOMPARE_RETRY_TIMES = 1,
  CRYPTOCOMPARE_TIMEOUT = 3000,
  MEMORY_CACHE_TTL = 3600000,
  NODE_ENV = 'development',
  PORT = 3000,
} = process.env;

const env = {
  CRYPTOCOMPARE_RETRY_DELAY,
  CRYPTOCOMPARE_RETRY_TIMES,
  CRYPTOCOMPARE_TIMEOUT,
  MEMORY_CACHE_TTL,
  NODE_ENV,
  PORT,
  ...process.env,
};


module.exports = env;
